# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fc703ca03b4109834533f79f8c10ddd8b5dd1ec3a032f5bc2ca808d1179170e74ec581fa8d106af3ed82bc7619a70c774d5eaea63f57174a8750b663a495e0b

test:
  secret_key_base: 3c70d07f186838a3750a48e48845831475d97d8e1117b605eb56f1a85132e05fad87994d27dd94f2da194a800f3a1a1fc9aa37345d3599f2df1f0e754cbed826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
